name: onscreen_keypad
description: A customizable on-screen numeric keypad for Flutter apps. Ideal for PIN entry, authentication screens, and custom input fields with haptic feedback support.
version: 1.0.2+5
homepage: https://github.com/Henrydykee/on-screen-keypad.git


environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"





dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  haptic_feedback: ^0.5.1+1



